### PR TITLE
Update State using setState()

### PR DESCRIPTION
**Pull request by mohsinht**

### CODE REVIEW

**Comment by mpociot** [comment]
Thanks for your PRs - can you tell me why this is better than modifying the state directly?

**Comment by mohsinht** [comment]
I was getting an error when I ran 'npm rum dev' on my computer. I've
reported the issue with the error msg I was getting.
I'm a React developer for over an year and I've  noticed that updating
state using setState not only keeps the dom reactive, it is very secure.

I went through all of the code and I changed many pieces to check what was
causing the problem. I noticed it was the state update. State values are
never recommended to be updated directly in React. I changed the lines
where state was updated and the error never came again.

Test it before merging in the master repo. I've tested on two machines and
its working fine now.

**Comment by mohsinht** [comment]
This is the issue: https://github.com/botman/web-widget/issues/14

**Comment by danlopez00** [comment]
> Thanks for your PRs - can you tell me why this is better than modifying the state directly?

The build fails. as mohsinht explained this will fix all build errors and I confirm

**Comment by mohsinht** [comment]
Please merge the branch.

**Pull request closed without merging**
